trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - .devops/workshop-release.yml
      - code/complete/GraphQL

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerInstaller@0
  displayName: "Install Docker"
  inputs:
    dockerVersion: '17.09.0-ce'

- task: KubectlInstaller@0
  displayName: "Install Kubectl"
  inputs:
    kubectlVersion: 'latest'

- task: Docker@2
  displayName: "Build Host Container"
  inputs:
    containerRegistry: '$(container-registry)'
    repository: 'ccc-oss-graphqlworkshop'
    command: 'buildAndPush'
    Dockerfile: 'code/complete/GraphQL/dockerfile'
    buildContext: 'code/complete/GraphQL'

- task: Kubernetes@1
  displayName: "Deploy Demo Service"
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '$(aks-cluster)'
    namespace: 'ccc-oss'
    command: 'apply'
    useConfigurationFile: true
    configurationType: 'inline'
    inline: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ccc-oss-graphqlworkshop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ccc-oss-graphqlworkshop
        template:
          metadata:
            labels:
              app: ccc-oss-graphqlworkshop
          spec:
            containers:
              - image: $(container-registry-domain)/ccc-oss-graphqlworkshop:$(Build.BuildId)
                resources:
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
                  requests:
                    memory: "64Mi"
                    cpu: "1m"
                name: ccc-oss-graphqlworkshop
                ports:
                  - containerPort: 80

      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: ccc-oss-graphqlworkshop
      spec:
        type: ClusterIP
        ports:
        - port: 80
        selector:
          app: ccc-oss-graphqlworkshop
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

