name: graphql-workshop

services:
  graphql-workshop-postgres:
    container_name: graphql-workshop-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: graphql_workshop
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: graphql_workshop
    networks: [graphql-workshop]
    ports: ["5432:5432"]
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

networks:
  graphql-workshop:
    name: graphql-workshop

volumes:
  postgres-data:
